name: Anchore Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Build
      run: docker build . --file Dockerfile --tag testrepo/testimage:latest
    - uses: anchore/scan-action@v1
      with:
        image-reference: "testrepo/testimage:latest"
        dockerfile-path: "./Dockerfile"
        fail-build: false
    - name: install json-to-html
      run: | 
         npm install json-to-html -g
         json test --json | json-to-html -o result.html
         mkdir downloads
         pwd
         cp -v /home/runner/*/*/*/*.html /home/runner/work/*/*/downloads

      # save the HTML in the artifact
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with:
          name: results
          path: downloads
